server:
    port: 8001
    context-path: /


zuul:
  routes:
    oauth:
      path: /auth/**
      url: http://localhost:8008/auth/
    stockservice:
      path: /stockservice/**
      url: http://localhost:8011/stockservice/
    orderservice:
      path: /orderservice/**
      url: http://localhost:8012/orderservice/


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: rs1
      clientSecret: 
      accessTokenUri: http://localhost:8081/authserver/oauth/token
      userAuthorizationUri: http://localhost:8081/authserver/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/authserver/user/me



      