server:
  port: 8008
  contextPath: /authserver

security:
  basic:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ # 服务注册中心地址
  instance:
    preferIpAddress: true

spring:
  application:
    name: auth-server # 服务名称
  datasource:
    dbcp2.validation-query: select 1 
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/oauth2server?stringtype=unspecified
    name: oauth2server
    username: pgdbo
    password: sql


mybatis.configuration:
  map-underscore-to-camel-case: true
  default-fetch-size: 100
  default-statement-timeout: 30

# ENDPOINTS CORS CONFIGURATION (EndpointCorsProperties)
# endpoints.cors:
#  allow-credentials: true # Set whether credentials are supported. When not set, credentials are not supported.
#  allowed-headers: '*' # Comma-separated list of headers to allow in a request. '*' allows all headers.
#  allowed-methods: '*' # Comma-separated list of methods to allow. '*' allows all methods.
#  allowed-origins: '*' # Comma-separated list of origins to allow. '*' allows all origins. When not set, CORS support is disabled.
  # exposed-headers: * # Comma-separated list of headers to include in a response.
#  max-age: 1800 
