server:
  port: 8009
  contextPath: /auth

security:
  basic:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry:8000/eureka/ # 服务注册中心地址
  instance:
    preferIpAddress: true
  
spring:
  application:
    name: auth-server-jwt # 服务名称
  datasource:
    dbcp2.validation-query: select 1 
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/oauth2server?stringtype=unspecified
    name: oauth2server
    username: pgdbo
    password: sql

logging:
  file: /web/logs/auth2-server.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    cn.devmgr: TRACE
    org.springframework: INFO
  
mybatis.configuration:
  map-underscore-to-camel-case: true
  default-fetch-size: 100
  default-statement-timeout: 30